title: CV
author: 黃昱維
email: worldmaker18349276@gmail.com
description: Updated April 2023

github_username:  worldmaker18349276
linkedin_username: 昱維-黃-3a1326132

show_excerpts: false

header_pages:
  - about.html

theme: minima
